### ISSUE TITLE
add region

### ISSUE THREAD

**Issue by giloser** [ziirish/OctoPrint-TuyaSmartplug#9]
Hi, 

after a long search to get the local key I finally get them but I got an network error on the log when I tried to send a command.
To get my localkey I had to use the region option with eu as value.

Could this be the reason of my error?

thanks a lot

**Comment by ziirish** [comment]
Hello,

I don't think regions have anything to do with your problem.
This plugin interacts directly with your plug, that's why it needs is local ip address.

Now there are mainly two things that can trigger connection error:

- either there is a running application interacting with your plug (there can be only one connection)
- or you need to use version 3.3 of the protocol
- (or both)

**Comment by giloser** [comment]
Hi thanks for the quick answer,

so I cannot have them in the apps like smart life and in octoprint?

thanks

**Comment by ziirish** [comment]
Yes you can, but you have to make sure the app is not running when you want octoprint to be able to control it.
